---
- name: Create data source creation script
  template: >
    src=create_data_source.py.j2
    dest={{ cfg_working_dir }}/{{ cfg_domain_name }}/create_data_source.py
    owner={{ cfg_wls_user }}
    group={{ cfg_wls_group }}

- name: Create the data source
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ cfg_working_dir }}/{{ cfg_domain_name }}/create_data_source.py"
  args:    
    chdir: "{{ cfg_wlst_bin_dir }}"