---
- url: s3://sps-build-deploy/ansible/jrockit-0.1.0.tgz
  paths:
    - from: .
      to: roles/jrockit
- url: s3://sps-build-deploy/ansible/weblogic-0.0.2.tgz
  paths:
    - from: .
      to: roles/weblogic
- url: s3://sps-build-deploy/ansible/olprep-0.0.2.tgz
  paths:
    - from: .
      to: roles/olprep
