---
# file: jms/tasks/create_domain.yml

- name: Create admin server configuration script
  template: >
    src=configure_admin_server.py.j2
    dest={{ cfg_working_dir }}/{{ cfg_domain_name }}/configure_admin_server.py
    owner={{ cfg_wls_user }}
    group={{ cfg_wls_group }}

- name: Configure the admin server
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ cfg_working_dir }}/{{ cfg_domain_name }}/configure_admin_server.py"
  args:    
    chdir: "{{ cfg_wlst_bin_dir }}"
