---
- name: Create data source creation script
  template: >
    src=create_data_source.py.j2
    dest={{ jms_working_dir }}/{{ jms_domain_name }}/create_data_source.py
    owner={{ jms_wls_user }}
    group={{ jms_wls_group }}

- name: Create the data source
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ jms_working_dir }}/{{ jms_domain_name }}/create_data_source.py"
  args:    
    chdir: "{{ jms_wlst_bin_dir }}"

- name: Cleanup script
  file:
    path: "{{ jms_working_dir }}/{{ jms_domain_name }}/create_data_source.py"
    state: absent