---
- name: Create JMS server creation script
  template: >
    src=create_jms_server.py.j2
    dest={{ jms_working_dir }}/{{ jms_domain_name }}/create_jms_server.py
    owner={{ jms_wls_user }}
    group={{ jms_wls_group }}

- name: Create the JMS server
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ jms_working_dir }}/{{ jms_domain_name }}/create_jms_server.py"
  args:    
    chdir: "{{ jms_wlst_bin_dir }}"

- name: Cleanup script
  file:
    path: "{{ jms_working_dir }}/{{ jms_domain_name }}/create_jms_server.py"
    state: absent