---
# file: jms/tasks/create_domain.yml

- name: Create domain creation python script
  template: >
    src=create_domain.py.j2
    dest={{ cfg_working_dir }}/{{ cfg_domain_name }}/create_domain.py
    owner={{ cfg_wls_user }}
    group={{ cfg_wls_group }}

- name: Create domain
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ cfg_working_dir }}/{{ cfg_domain_name }}/create_domain.py"
  args:    
    chdir: "{{ cfg_wlst_bin_dir }}"
    creates: "{{ cfg_domain_path }}/{{ cfg_domain_name }}"
