---
- name: Create domain JTA modification script
  template: >
    src=modify_domain.py.j2
    dest={{ jms_working_dir }}/{{ jms_domain_name }}/modify_domain.py
    owner={{ jms_wls_user }}
    group={{ jms_wls_group }}

- name: Modify the domain JTA
  sudo: yes
  sudo_user: oracle
  command: "./wlst.sh {{ jms_working_dir }}/{{ jms_domain_name }}/modify_domain.py"
  args:    
    chdir: "{{ jms_wlst_bin_dir }}"

- name: Cleanup script
  file:
    path: "{{ jms_working_dir }}/{{ jms_domain_name }}/modify_domain.py"
    state: absent