---
# file: jms/tasks/start_admin_server.yml

# TODO: convert this to a service
- name: start weblogic
  sudo: yes
  sudo_user: oracle
  shell: "/usr/bin/nohup ./bin/startWebLogic.sh > {{ cfg_working_dir }}/{{ cfg_domain_name }}/startWebLogic.log &"
  args:    
    chdir: "{{ cfg_domain_path }}/{{ cfg_domain_name }}"

- name: Wait for weblogic to start up
  wait_for: 
    port: "{{cfg_admin_server_listen_port}}"
    delay: 5

- name: Wait for /console to come up
  uri: 
    url: "http://localhost:{{cfg_admin_server_listen_port}}/console"
    status_code: 200
    timeout: 300
    async: 300
    poll: 10
    register: adminUp