---
# file: jms/tasks/start_node_manager.yml

# TODO: convert this to a service
- name: start node manager
  sudo: yes
  sudo_user: oracle
  shell: "/usr/bin/nohup ./startNodeManager.sh > {{ cfg_working_dir }}/{{ cfg_domain_name }}/startNodeManager.log &"
  args:    
    chdir: "{{ cfg_wlst_server_bin_dir }}"

- name: Wait for node manager to start up
  wait_for: 
    port: "{{ cfg_node_manager_listen_port }}"
    delay: 5